name: ci-cd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest test_app.py

      - name: Install AWS CLI and Elastic Beanstalk CLI
        run: |
          pip install awscli
          pip install awsebcli --upgrade --user
          export PATH=$PATH:/home/runner/.local/bin

      - name: Deploy to AWS
        if: success()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-south-1'
          EB_APP_NAME: 'flask-app'
          EB_ENV_NAME: 'flask-app-env'
        run: |
          eb init -p python-3.11 $EB_APP_NAME --region $AWS_REGION
          eb deploy --staged
